<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;


    protected $table = 'users';
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'username',
        'email',
        'password',
    ];

    // returns all entitlements associated with this user
    public function entitlements()
    {
      return $this->belongsToMany(Entitlements::class, 'user_entitlements', 'user_id', 'entitlement_id');
    }

    // returns all radars associated with this user
    public function projects()
    {
      return $this->belongsToMany(Radar::class, 'working_on', 'user_id', 'radar_id');
    }

    // checks if user has moderator role
    public function isModerator()
    {
      $entitlements = $this->entitlements();

      if ($entitlements->where('entitlement_id', 2)->count()!==0) {
        return true;
      } else {
        return false;
      }
    }



    // Generated by Laravel, not needed for now
    // /**
    //  * The attributes that should be hidden for serialization.
    //  *
    //  * @var array<int, string>
    //  */
    // protected $hidden = [
    //     'password',
    //     'remember_token',
    // ];
    //
    // /**
    //  * The attributes that should be cast.
    //  *
    //  * @var array<string, string>
    //  */
    // protected $casts = [
    //     'email_verified_at' => 'datetime',
    // ];
}
